import Head from "next/head";
import { useState } from "react";
import ScrollProgress from "./ScrollProgress";
import Header from "./Header";
import Footer from "./Footer";

type LayoutProps = {
  children: React.ReactNode;
};

export default function Layout({ children }: LayoutProps) {
  const [isNavOpen, setIsNavOpen] = useState(false);

  return (
    <>
      <Head>
        <title>Snorkell.ai</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={`my-app home-dark ${isNavOpen ? "body-active" : ""}`}>
        <Header isNavOpen={isNavOpen} setIsNavOpen={setIsNavOpen} />

        <main>{children}</main>

        <Footer />
        
        <ScrollProgress />
      </div>
    </>
  );
}
